name: grmap
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - amply
  - annotated-types
  - appdirs
  - argparse-dataclass
  - attrs
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - charset-normalizer
  - click
  - coin-or-cbc
  - coin-or-cgl
  - coin-or-clp
  - coin-or-osi
  - coin-or-utils
  - coincbc
  - colorama
  - coloredlogs
  - colormath
  - conda-inject
  - configargparse
  - connection_pool
  - contourpy
  - cycler
  - docutils
  - double-conversion
  - dpath
  - eido
  - exceptiongroup
  - expat
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - gitdb
  - gitpython
  - h2
  - hpack
  - htslib
  - humanfriendly
  - humanize
  - hyperframe
  - icu
  - idna
  - immutables
  - importlib-metadata
  - importlib_resources
  - iniconfig
  - jinja2
  - jsonschema
  - jsonschema-specifications
  - jupyter_core
  - kaleido-core
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libblas
  - libcblas
  - libclang13
  - libcurl
  - libdeflate
  - libedit
  - libexpat
  - libffi
  - libiconv
  - libjpeg-turbo
  - liblapack
  - liblapacke
  - libpng
  - libpq
  - libsqlite
  - libssh2
  - libtiff
  - libuuid
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - logmuse
  - markdown
  - markdown-it-py
  - markupsafe
  - mathjax
  - matplotlib
  - matplotlib-base
  - mdurl
  - multiqc
  - munkres
  - narwhals
  - natsort
  - nbformat
  - ncurses
  - networkx
  - nspr
  - nss
  - numpy
  - openjpeg
  - openldap
  - openssl
  - packaging
  - pandas
  - pcre2
  - pephubclient
  - peppy
  - pillow
  - pip
  - pixman
  - pkgutil-resolve-name
  - plac
  - platformdirs
  - plotly
  - pluggy
  - psutil
  - pulp
  - pyaml-env
  - pycparser
  - pydantic
  - pydantic-core
  - pygments
  - pyparsing
  - pysocks
  - pytest
  - python=3.12
  - python-dateutil
  - python-dotenv
  - python-fastjsonschema
  - python-kaleido
  - python-tzdata
  - python_abi
  - pytz
  - pyyaml
  - qhull
  - readline
  - referencing
  - regex
  - requests
  - reretry
  - rich
  - rich-click
  - rpds-py
  - samtools
  - setuptools
  - shellingham
  - six
  - slack-sdk
  - smart_open
  - smmap
  - snakemake
  - snakemake-interface-common
  - snakemake-interface-executor-plugins
  - snakemake-interface-logger-plugins
  - snakemake-interface-report-plugins
  - snakemake-interface-storage-plugins
  - snakemake-minimal
  - spectra
  - sqlite
  - tabulate
  - throttler
  - tiktoken
  - tk
  - tomli
  - tornado
  - tqdm
  - traitlets
  - typeguard
  - typer
  - typer-slim
  - typing-extensions
  - typing-inspection
  - typing_extensions
  - tzdata
  - ubiquerg
  - unicodedata2
  - urllib3
  - veracitools
  - wheel
  - wrapt
  - yaml
  - yte
  - zipp
  - zstandard
  - zstd