site_name: GRMAP
site_description: 'Documentation for matching sequencing reads to a reference genome and annotating the matched sequences with genomic features.'
site_author: 'Abhinav Mishra'
site_url: https://bibymaths.github.io/grmap
use_directory_urls: false
repo_url: https://github.com/bibymaths/grmap

theme:
  name: readthedocs
  language: en
  features:
    - navigation.tabs
    - content.code.copy

nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - Pipeline Overview:
      - Workflow Diagram: workflow.md
      - Process Details: processes.md
  - Configuration:
      - Parameters: parameters.md
  - Results:
      - Output Structure: outputs.md
  - References: references.md
  - About: about.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite

plugins:
  - search

watch:
  - docs

copyright: >
  Copyright &copy; 2025 <a href="https://bibymaths.github.io">Abhinav Mishra</a>.